apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "clamav-api.fullname" . }}
  labels:
    {{- include "clamav-api.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "clamav-api.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "clamav-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "clamav-api.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: GIN_MODE
              value: {{ .Values.config.ginMode }}
            - name: CLAMAV_DEBUG
              value: {{ .Values.config.debug | quote }}
            - name: CLAMAV_SOCKET
              value: {{ .Values.config.socket }}
            - name: CLAMAV_MAX_SIZE
              value: {{ .Values.config.maxSize | quote }}
            - name: CLAMAV_HOST
              value: {{ .Values.config.host }}
            - name: CLAMAV_PORT
              value: {{ .Values.config.port | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health-check
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health-check
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: data
              mountPath: /var/lib/clamav
            - name: socket
              mountPath: /var/run/clamav
            - name: tmp
              mountPath: /tmp
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: socket
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        {{- if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
        {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
        {{- with .Values.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      spec:
        accessModes: 
          - {{ .Values.persistence.accessMode }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- with .Values.persistence.selector }}
        selector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
  {{- end }} 
