apiVersion: v2
appVersion: 2.7.4
name: influxdb2-backup
description: A Helm chart for InfluxDB v2 backup
type: application
version: 1.0.0
maintainers:
  - name: vukomir
    email: vukomir@ianculov.ro
icon: https://avatars0.githubusercontent.com/u/5713248?s=200&v=4
